### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by lwchkg**
- Changed documentation file copy command because original command doesn't work with wildcards. (See https://cmake.org/cmake/help/latest/manual/cmake.1.html for details.)
- Fixed help file path in Main.cpp and Main.js.

### CODE REVIEW

**Comment by lwchkg** [comment]
@enz I have successfully built Pentobi in Windows 10. Let's see how can I send you the binary for release. (A ZIP file cannot be uploaded here. Anyway, I'll aim at setting up AppVeyor build soon.)

BTW, please help me to check if this breaks anything in Linux.

**Comment by lwchkg** [comment]
Anyway, here's my build instructions:

1. Install VS 2019 Community, Qt (6.2.3 currently), msys2 and cmake.
2. In msys2 MinGW-64 prompt: `pacman -S mingw-w64-x86_64-gettext mingw-w64-x86_64-itstool mingw-w64-x86_64-docbook-xsl mingw-w64-x86_64-librsvg`
3. Make a `winbuild.bat` in pentobi root directory with the contents below:
```bat
@ECHO OFF
SETLOCAL
SET CMAKE_DIR=C:\Program Files\CMake\bin
SET QT_DIR=C:\Qt\6.2.3\msvc2019_64
SET MINGW_DIR=C:\msys64\mingw64
SET DOCBOOK_XSL_DIR=%MINGW_DIR%\share\xml\docbook\xsl-stylesheets-1.79.2
SET MSBUILD_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\

SET OUTPUT_DIR=".\build\x64"

SET PATH=%CMAKE_DIR%;%MINGW_DIR%\bin;%PATH%

cmake -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_PREFIX_PATH="%QT_DIR%" -DDOCBOOKXSL_DIR="%OUTPUT_DIR%\docbook-xsl-stylesheet" -G "Visual Studio 16 2019" -S . -B "%OUTPUT_DIR%"
if exist "%OUTPUT_DIR%\docbook-xsl-stylesheet" rmdir "%OUTPUT_DIR%\docbook-xsl-stylesheet"
mklink /d "%OUTPUT_DIR%\docbook-xsl-stylesheet" "%DOCBOOK_XSL_DIR%"

"%MSBUILD_DIR%\msbuild" "%OUTPUT_DIR%\pentobi.sln"
rmdir "%OUTPUT_DIR%\docbook-xsl-stylesheet"

mkdir "%OUTPUT_DIR%\Release"
copy /b "%OUTPUT_DIR%\pentobi\Release\pentobi.exe" "%OUTPUT_DIR%\Release"
"%QT_DIR%\bin\windeployqt" --release --qmldir "%~dp0pentobi\qml" "%OUTPUT_DIR%\Release\pentobi.exe"

ENDLOCAL
```
4. Run the script above. (I hope the instruction is complete.)

**Comment by enz** [comment]
Unfortunatley, this breaks Linux because helpDir is an absolute path starting with a slash. For example, if PENTOBI_HELP_DIR is /usr/share/doc/pentobi/help, your url would become file:////usr/local/share/doc/pentobi/help/C/index.html, which has four slashes after the URL scheme, which doesn't work. It might be necessary to handle Windows as a special case in Main.js:help()

I manually committed your fix for the wrong argument of QFile::exists() to both v20-fixes and master, because it was a bug that also affected Linux, although I use the relative path only during development to test the program without installation, so the Linux packages should not be affected by this bug.

**Comment by lwchkg** [comment]
Thanks for the quick reply.

How about prepending the path with a slash ONLY if it starts with a letter? So paths like 'C:/pentobi/...' becomes 'file://' + '/' + 'C:/...' while '/usr/...' becomes 'file://' + '/usr...'.

**Comment by enz** [comment]
Sure that would work too, but why not make it explicit that we are handling Windows here? You can check the platform in Javascript with `if (Qt.platform == "windows")`. Also, please create a separate branch for your pull request.

What about your changes to pentobi/docbook/CMakeLists.txt? Are those only cleanup or why doesn't it work on Windows?

**Comment by enz** [comment]
Sorry, I just noticed that you explained the changes to pentobi/docbook/CMakeLists.txt above.

**Comment by enz** [comment]
About Windows binaries: I don't use Windows and wouldn't want to sign and release binaries that I haven't compiled myself. But if you want to maintain Windows binaries of Pentobi on a third site, I can add a link to it from the Pentobi homepage.

**Comment by lwchkg** [comment]
Thanks for pointing out about Qt and the pull request thing. I'm a newbie of those. (Looks like my fork is so polluted after merging your new code, so I need to re-fork and create a new pull request.)

Anyway, that JS code should be `Qt.platform.os == "windows"`. I still have no idea how to find this information from the Qt docs. :-(

**Comment by lwchkg** [comment]
Closing because another pull request is made. New discussion please go to #17 .

**Pull request closed without merging**
