### PR TITLE
Add AppVeyor build configuration

### PR DESCRIPTION
**Pull request by lwchkg**
This is an AppVeyor build configuration for the Windows build:

- The Windows build is created as an artifact called "pentobi.zip".
  (e.g. https://ci.appveyor.com/project/lwchkg/pentobi/build/artifacts)
- That "pentobi.zip" can be used as an official Windows release.
- To enable the builds as CI, add the repo to AppVeyor. This should be just a few clicks if GitHub is used to sign in AppVeyor.

### CODE REVIEW

**Comment by enz** [comment]
Is there a reason why this needs to be included in the Pentobi sources? I would prefer to do source releases and "outsource" the creation of binary packages to external projects (with the exception of the Android packages, which I maintain myself).

If you look at the list of Pentobi packages at [Repology](https://repology.org/project/pentobi/versions), all of them have special configuration files for building the binary packages and it is not customary to include these files into the repository of the application.

**Comment by lwchkg** [comment]
I wonder if you are used to the concept of Continuous Integration (all your repos are having quite a long history). The idea of CI is to test the code at every commit so bugs and regressions can be detected and fixed quickly. In contrast to manual testing, CI systems can automatically test the code for multiple platforms (i.e. Linux, Windows, Android, etc., and different versions of Qt) for every commit.

If any of the CI bots breaks, you will automatically receive a report, and can inspect the log to know what needs to be fixed. In GitHub, you can also do CI for every pull request, and show the CI status in the PR page.

_**The files I submitted tells AppVeyor (a CI system) how to "test" the code**_, but the current "tests" only including building the binary. This is still better than having no tests at all, at least in the form of guarantee that your code can build correctly. Anyway, AppVeyor is a good CI system for Windows builds. You should probably create another config in Travis CI for testing in Linux (maybe also FreeBSD).

Ideally, in addition of building, you also define some tests that runs with those CI systems. There are many testing frameworks for C++, e.g. GoogleTest and Boost.Test, which makes creation of testing code easier.

(I was enlightened with the idea of CI when I contributed to Chromium. :-) They require adding tests for every code you add and most bugs you fix.)

**Comment by lwchkg** [comment]
I'm a bit out of date. Now Travis CI appears not so good recently. People use GitHub Actions or CircleCi for testing instead.

**Comment by enz** [comment]
Let's put aside the big idea of CI with lots of automated tests and many supported platforms. Pentobi does not compare to a project the size of Chromium.

What I am trying to say is that I cannot be the maintainer of a Windows version of Pentobi because I don't use Windows. Knowing that the code compiles is not enough and with GUI code, you need some amount of interactive testing.

I would be happy if you want to become the maintainer of a Windows version of Pentobi, but I would prefer that you do it as an independent downstream project in a separate repository. Then you can test it on Windows, fix problems, create Windows packages and handle Windows-related bug reports without that it creates additional work for me. I will try to answer any questions about the code and merge pull request if it makes sense to apply them upstream.

For now, I will leave this issue open. I am currently not in the mood to do game development but I might try out the AppVeyor build some time in the future.

**Comment by lwchkg** [comment]
Just feel free to keep this open for as long as you want.

Fortunately I can still use AppVeyor downstream without this file. (This file is generated from AppVeyor UI.) With this I am now confident enough to maintain the Windows build. See my other PR for details.

**Comment by enz** [comment]
If it is not necessary to have the AppVeyor file in this repository, I will close this pull request.

Great that you want to maintain the Windows version. I added a link from the Pentobi homepage, so that people can easily find it. BTW, generally it is better to use the stable branch (currently v20-fixes) for releases because the master branch can be buggy at times or contain unfinished work. However, currently it is ok to use the master branch because I don't do much work anyway and the next release will very likely be version 21.0.

Thanks for your work!

**Pull request closed without merging**
